### PR TITLE
PupilCapture

### PR DESCRIPTION
**Pull request by mattem86**
Interface for capture of Pupil labs cameras with C++, primarily for windows

### CODE REVIEW

**Comment by willpatera** [comment]
@mattem86 I would be happy to merge this. However the name `Pupil Capture` is the name of one of our software applications. As @papr notes in his issue, if you are willing to consider re-naming so that others will clearly understand the differences between Pupil Capture and your C++ interface, that would be greatly appreciated :smile:

**Comment by mattem86** [comment]
@papr I would suggest a name like "PupilCamC++" or something like that for the entry – maybe just add a comment, that this is not affiliated with Pupil labs.

**Comment by willpatera** [comment]
@mattem86 thanks for the response. Could you change your repo name to `PupilCamC++` or something similar to avoid confusion within the community?

**Comment by mattem86** [comment]
@willpatera I know, this is not my repo, so I can't change it.

**Comment by willpatera** [comment]
noted, thanks @mattem86

**Pull request merged**
